/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentaltoolkit.Frame;

import Controlador.Usuario;
import Validaciones.Validador;
import java.awt.Window;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author EHef_
 */
public class LoginDoc extends javax.swing.JPanel {

    /**
     * Creates new form LoginDoc
     */
    public LoginDoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CAMPOUSUARIO = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        CAMPOCONTRA = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LOGIN DOCTOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 150, 50));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 660, 10));

        CAMPOUSUARIO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CAMPOUSUARIO.setForeground(new java.awt.Color(255, 153, 102));
        CAMPOUSUARIO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CAMPOUSUARIO.setText("CORREO");
        CAMPOUSUARIO.setBorder(null);
        CAMPOUSUARIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CAMPOUSUARIOMouseClicked(evt);
            }
        });
        CAMPOUSUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMPOUSUARIOActionPerformed(evt);
            }
        });
        jPanel1.add(CAMPOUSUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 360, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentaltoolkit/Image/llave-de-la-puerta.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentaltoolkit/Image/empleados (2).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jButton1.setText("ENTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 90, 40));

        jSeparator2.setForeground(new java.awt.Color(204, 102, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 360, 20));

        jSeparator3.setForeground(new java.awt.Color(204, 102, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 360, 20));

        CAMPOCONTRA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CAMPOCONTRA.setForeground(new java.awt.Color(255, 153, 102));
        CAMPOCONTRA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CAMPOCONTRA.setText("contraseña");
        CAMPOCONTRA.setBorder(null);
        CAMPOCONTRA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CAMPOCONTRAMouseClicked(evt);
            }
        });
        jPanel1.add(CAMPOCONTRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 360, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 102, 0));
        jLabel4.setText("CONTRASEÑA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 102, 0));
        jLabel6.setText("CORREO DE USUARIO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 170, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void CAMPOUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMPOUSUARIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAMPOUSUARIOActionPerformed

    private void CAMPOUSUARIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAMPOUSUARIOMouseClicked
     CAMPOUSUARIO.setText("");
    }//GEN-LAST:event_CAMPOUSUARIOMouseClicked

    private void CAMPOCONTRAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAMPOCONTRAMouseClicked
     CAMPOCONTRA.setText("");   // TODO add your handling code here:
    }//GEN-LAST:event_CAMPOCONTRAMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Usuario Doctor = new Usuario();
        Validador Va = new Validador();
        new Thread(() -> {
            if(Va.validateEMAIL(CAMPOUSUARIO.getText())){
                try {
                 File file = new File("");
                 String a = "";
                    if(System.getProperty("os.name").equals("Linux")){        
                        a=file.getCanonicalFile().toString()+"/src/dentaltoolkit/Image/loading.gif";
                    }else{
                        a = file.getCanonicalFile().toString()+"\\src\\dentaltoolkit\\Image\\loading.gif";
                    }
                 ImageIcon loading = new ImageIcon(a);
                 JLabel A =new JLabel("Cargando... ", loading, JLabel.CENTER);
                 String RESP=Doctor.LoginUsuario(CAMPOUSUARIO.getText(),CAMPOCONTRA.getText(),2);
                 if(!RESP.equals("")){
                     Doctor.Nombre=RESP;
                     JOptionPane.showMessageDialog(this, "¡Ingreso exitoso!");
                     JComponent comp = (JComponent) evt.getSource();
                     Window win = SwingUtilities.getWindowAncestor(comp);
                     win.dispose();
                     Admin Ad =new Admin(Doctor);
                     Ad.show();
                 }else{
                     JOptionPane.showMessageDialog(this, "¡Error en credenciales!");
                     A.setVisible(false);
                     this.setVisible(true);
                 }} catch (IOException ex) {
                        Logger.getLogger(LoginAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                   Logger.getLogger(LoginAdmin.class.getName()).log(Level.SEVERE, null, ex);
               }
            }else{
                JOptionPane.showMessageDialog(this, "¡Correo invalido!");
            }
         }).start();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CAMPOCONTRA;
    private javax.swing.JTextField CAMPOUSUARIO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
