/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentaltoolkit.Frame;

/**
 *
 * @author EHef_
 */
public class Panel1 extends javax.swing.JPanel {

    /**
     * Creates new form Panel1
     */
    public Panel1() {
        initComponents();
        //rsscalelabel.RSScaleLabel.setScaleLabel(img1, "C:\\Users\\EHef_\\OneDrive\\Datos adjuntos de correo electrónico\\Documentos\\NetBeansProjects\\DentalToolkit\\src\\dentaltoolkit\\Image\\Logo.png");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P1 = new javax.swing.JPanel();
        img1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P1.setBackground(new java.awt.Color(255, 255, 255));
        P1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 102)));
        P1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentaltoolkit/Image/Logo2.png"))); // NOI18N
        P1.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -10, 760, 580));

        add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 580));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P1;
    private javax.swing.JLabel img1;
    // End of variables declaration//GEN-END:variables
}
